/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banvexe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huu Nhan
 */
public class quanli extends javax.swing.JFrame {

    /**
     * Creates new form quanli
     */
    public quanli() {
        initComponents();
        //================= set label đầu tiên
        switchPanels(jPanelVe);
        
        setColor(jPanelList1);
        resetColor(jPanelList2);
        resetColor(jPanelList3);
        resetColor(jPanelList4);
        resetColor(jPanelList5);
        resetColor(jPanelList6);
        resetColor(jPanelList7);
        resetColor(jPanelList8);
        //=====================================
        
        layChuyenXe();
        layTuyenTram();
        layNhanVien();
        layTuyen();
        layMail();
        layVe();
        layXe();
        layThongKeTheoNgayTT();
        layThongKeTheoNgayVSV();
        layThongKeTheoNgayVT();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jDialogTuyenTram = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldHieuChinhTuyen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldHieuChinhTram = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLayeredPaneQuanLy = new javax.swing.JLayeredPane();
        jPanelMail = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMail = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanelNhanVien = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNhanVien = new javax.swing.JTable();
        jPanelTuyen = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableTuyen = new javax.swing.JTable();
        jPanelChuyen = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableChuyen = new javax.swing.JTable();
        jPanelXe = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableXe = new javax.swing.JTable();
        jPanelTuyenTram = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableTuyenTram = new javax.swing.JTable();
        jPanelVe = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVe = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanelThongKe = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableThongKeTheoNgayTT = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTableThongKeTheoNgayVT = new javax.swing.JTable();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTableThongKeTheoNgayVSV = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanelList = new javax.swing.JPanel();
        jPanelList1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelList2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelList3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelList4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanelList5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanelList7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanelList8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanelList6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField1");

        jTextField3.setText("jTextField1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jLabel3.setText("Tuyến");

        jLabel4.setText("Trạm");

        jButton3.setText("Thêm");

        jButton4.setText("Sửa");

        jButton5.setText("Xóa");

        javax.swing.GroupLayout jDialogTuyenTramLayout = new javax.swing.GroupLayout(jDialogTuyenTram.getContentPane());
        jDialogTuyenTram.getContentPane().setLayout(jDialogTuyenTramLayout);
        jDialogTuyenTramLayout.setHorizontalGroup(
            jDialogTuyenTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTuyenTramLayout.createSequentialGroup()
                .addGroup(jDialogTuyenTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogTuyenTramLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jDialogTuyenTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogTuyenTramLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(73, 73, 73)
                                .addComponent(jTextFieldHieuChinhTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogTuyenTramLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(73, 73, 73)
                                .addComponent(jTextFieldHieuChinhTram, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jDialogTuyenTramLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jDialogTuyenTramLayout.setVerticalGroup(
            jDialogTuyenTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTuyenTramLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jDialogTuyenTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldHieuChinhTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jDialogTuyenTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldHieuChinhTram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jDialogTuyenTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(62, 62, 62))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("VEXEBUS");

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Nhap mon cong nghe phan mem\\banvexe\\icons8_bus_40px_1.png")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Thoát");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 569, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel9)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPaneQuanLy.setLayout(new java.awt.CardLayout());

        jTableMail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email", "Tên KH", "SDT", "Pass", "Số Dư"
            }
        ));
        jScrollPane3.setViewportView(jTableMail);

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMailLayout = new javax.swing.GroupLayout(jPanelMail);
        jPanelMail.setLayout(jPanelMailLayout);
        jPanelMailLayout.setHorizontalGroup(
            jPanelMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMailLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(jPanelMailLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMailLayout.setVerticalGroup(
            jPanelMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMailLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jButton1)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jLayeredPaneQuanLy.add(jPanelMail, "card3");

        jTableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Ngay Sinh", "Chức Vụ", "Mã Chuyến Xe"
            }
        ));
        jScrollPane1.setViewportView(jTableNhanVien);

        javax.swing.GroupLayout jPanelNhanVienLayout = new javax.swing.GroupLayout(jPanelNhanVien);
        jPanelNhanVien.setLayout(jPanelNhanVienLayout);
        jPanelNhanVienLayout.setHorizontalGroup(
            jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNhanVienLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanelNhanVienLayout.setVerticalGroup(
            jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNhanVienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jLayeredPaneQuanLy.add(jPanelNhanVien, "card4");

        jTableTuyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tuyến", "Điểm đi", "Điểm đến"
            }
        ));
        jScrollPane4.setViewportView(jTableTuyen);

        javax.swing.GroupLayout jPanelTuyenLayout = new javax.swing.GroupLayout(jPanelTuyen);
        jPanelTuyen.setLayout(jPanelTuyenLayout);
        jPanelTuyenLayout.setHorizontalGroup(
            jPanelTuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTuyenLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanelTuyenLayout.setVerticalGroup(
            jPanelTuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTuyenLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jLayeredPaneQuanLy.add(jPanelTuyen, "card5");

        jTableChuyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Chuyến Xe", "Mã Tuyến", "Tổng số chỗ đặt", "Ngày"
            }
        ));
        jScrollPane5.setViewportView(jTableChuyen);

        javax.swing.GroupLayout jPanelChuyenLayout = new javax.swing.GroupLayout(jPanelChuyen);
        jPanelChuyen.setLayout(jPanelChuyenLayout);
        jPanelChuyenLayout.setHorizontalGroup(
            jPanelChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChuyenLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanelChuyenLayout.setVerticalGroup(
            jPanelChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChuyenLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jLayeredPaneQuanLy.add(jPanelChuyen, "card6");

        jTableXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Biển số xe", "Mã Chuyến Xe"
            }
        ));
        jScrollPane7.setViewportView(jTableXe);

        javax.swing.GroupLayout jPanelXeLayout = new javax.swing.GroupLayout(jPanelXe);
        jPanelXe.setLayout(jPanelXeLayout);
        jPanelXeLayout.setHorizontalGroup(
            jPanelXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelXeLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanelXeLayout.setVerticalGroup(
            jPanelXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelXeLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLayeredPaneQuanLy.add(jPanelXe, "card8");

        jTableTuyenTram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tuyến", "Trạm"
            }
        ));
        jTableTuyenTram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTuyenTramMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jTableTuyenTram);

        javax.swing.GroupLayout jPanelTuyenTramLayout = new javax.swing.GroupLayout(jPanelTuyenTram);
        jPanelTuyenTram.setLayout(jPanelTuyenTramLayout);
        jPanelTuyenTramLayout.setHorizontalGroup(
            jPanelTuyenTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTuyenTramLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanelTuyenTramLayout.setVerticalGroup(
            jPanelTuyenTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTuyenTramLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLayeredPaneQuanLy.add(jPanelTuyenTram, "card9");

        jTableVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Vé", "Mã Chuyến Xe", "Số Chỗ Đặt", "Giá", "Nơi đi", "Nơi đến", "Email"
            }
        ));
        jScrollPane2.setViewportView(jTableVe);

        jButton2.setText("Hiệu chỉnh");

        javax.swing.GroupLayout jPanelVeLayout = new javax.swing.GroupLayout(jPanelVe);
        jPanelVe.setLayout(jPanelVeLayout);
        jPanelVeLayout.setHorizontalGroup(
            jPanelVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVeLayout.createSequentialGroup()
                .addGroup(jPanelVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVeLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVeLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanelVeLayout.setVerticalGroup(
            jPanelVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVeLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton2)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jLayeredPaneQuanLy.add(jPanelVe, "card9");

        jTableThongKeTheoNgayTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày", "Tổng tiền"
            }
        ));
        jScrollPane6.setViewportView(jTableThongKeTheoNgayTT);

        jTableThongKeTheoNgayVT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày", "Vé thường"
            }
        ));
        jScrollPane12.setViewportView(jTableThongKeTheoNgayVT);

        jTableThongKeTheoNgayVSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày", "Vé sinh viên"
            }
        ));
        jScrollPane13.setViewportView(jTableThongKeTheoNgayVSV);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 325, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống kê theo ngày", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tháng", "Số vé sinh viên", "Số vé thường", "Tổng tiền"
            }
        ));
        jScrollPane9.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống kê theo tháng", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Năm", "Số vé sinh viên", "Số vé thường", "Tổng tiền"
            }
        ));
        jScrollPane10.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 163, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 349, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống kê theo năm", jPanel3);

        javax.swing.GroupLayout jPanelThongKeLayout = new javax.swing.GroupLayout(jPanelThongKe);
        jPanelThongKe.setLayout(jPanelThongKeLayout);
        jPanelThongKeLayout.setHorizontalGroup(
            jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanelThongKeLayout.setVerticalGroup(
            jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jLayeredPaneQuanLy.add(jPanelThongKe, "card9");

        getContentPane().add(jLayeredPaneQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 80, 620, 520));

        jPanelList.setBackground(new java.awt.Color(54, 33, 89));
        jPanelList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelList1.setBackground(new java.awt.Color(85, 65, 118));
        jPanelList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelList1MousePressed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ticket_40px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vé");

        javax.swing.GroupLayout jPanelList1Layout = new javax.swing.GroupLayout(jPanelList1);
        jPanelList1.setLayout(jPanelList1Layout);
        jPanelList1Layout.setHorizontalGroup(
            jPanelList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelList1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelList1Layout.setVerticalGroup(
            jPanelList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelList.add(jPanelList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));

        jPanelList2.setBackground(new java.awt.Color(64, 43, 100));
        jPanelList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelList2MousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mail_account_40px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mail");

        javax.swing.GroupLayout jPanelList2Layout = new javax.swing.GroupLayout(jPanelList2);
        jPanelList2.setLayout(jPanelList2Layout);
        jPanelList2Layout.setHorizontalGroup(
            jPanelList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelList2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelList2Layout.setVerticalGroup(
            jPanelList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelList.add(jPanelList2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 40));

        jPanelList3.setBackground(new java.awt.Color(64, 43, 100));
        jPanelList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelList3MousePressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/staff_40px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nhân viên");

        javax.swing.GroupLayout jPanelList3Layout = new javax.swing.GroupLayout(jPanelList3);
        jPanelList3.setLayout(jPanelList3Layout);
        jPanelList3Layout.setHorizontalGroup(
            jPanelList3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelList3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelList3Layout.setVerticalGroup(
            jPanelList3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelList.add(jPanelList3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, -1));

        jPanelList4.setBackground(new java.awt.Color(64, 43, 100));
        jPanelList4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelList4MousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/journey_40px.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tuyến");

        javax.swing.GroupLayout jPanelList4Layout = new javax.swing.GroupLayout(jPanelList4);
        jPanelList4.setLayout(jPanelList4Layout);
        jPanelList4Layout.setHorizontalGroup(
            jPanelList4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelList4Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelList4Layout.setVerticalGroup(
            jPanelList4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelList.add(jPanelList4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, -1));

        jPanelList5.setBackground(new java.awt.Color(64, 43, 100));
        jPanelList5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelList5MousePressed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/adventure_40px.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Chuyến");

        javax.swing.GroupLayout jPanelList5Layout = new javax.swing.GroupLayout(jPanelList5);
        jPanelList5.setLayout(jPanelList5Layout);
        jPanelList5Layout.setHorizontalGroup(
            jPanelList5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelList5Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelList5Layout.setVerticalGroup(
            jPanelList5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelList.add(jPanelList5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, -1));

        jPanelList7.setBackground(new java.awt.Color(64, 43, 100));
        jPanelList7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelList7MousePressed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bus_40px.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Xe");

        javax.swing.GroupLayout jPanelList7Layout = new javax.swing.GroupLayout(jPanelList7);
        jPanelList7.setLayout(jPanelList7Layout);
        jPanelList7Layout.setHorizontalGroup(
            jPanelList7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelList7Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
        );
        jPanelList7Layout.setVerticalGroup(
            jPanelList7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelList.add(jPanelList7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 180, -1));

        jPanelList8.setBackground(new java.awt.Color(64, 43, 100));
        jPanelList8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelList8MousePressed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/statistics_40px.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Thống kê");

        javax.swing.GroupLayout jPanelList8Layout = new javax.swing.GroupLayout(jPanelList8);
        jPanelList8.setLayout(jPanelList8Layout);
        jPanelList8Layout.setHorizontalGroup(
            jPanelList8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelList8Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
        );
        jPanelList8Layout.setVerticalGroup(
            jPanelList8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelList.add(jPanelList8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 180, -1));

        jPanelList6.setBackground(new java.awt.Color(64, 43, 100));
        jPanelList6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelList6MousePressed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/connect_40px.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Tuyến Trạm");

        javax.swing.GroupLayout jPanelList6Layout = new javax.swing.GroupLayout(jPanelList6);
        jPanelList6.setLayout(jPanelList6Layout);
        jPanelList6Layout.setHorizontalGroup(
            jPanelList6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelList6Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
        );
        jPanelList6Layout.setVerticalGroup(
            jPanelList6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelList.add(jPanelList6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 180, -1));

        getContentPane().add(jPanelList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 179, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        //jLabel9.setBackground(Color.WHITE);
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanelList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelList1MousePressed
        // TODO add your handling code here:
        switchPanels(jPanelVe);
        
        setColor(jPanelList1);
        resetColor(jPanelList2);
        resetColor(jPanelList3);
        resetColor(jPanelList4);
        resetColor(jPanelList5);
        resetColor(jPanelList6);
        resetColor(jPanelList7);
        resetColor(jPanelList8);
    }//GEN-LAST:event_jPanelList1MousePressed

    private void jPanelList2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelList2MousePressed
        // TODO add your handling code here:
        switchPanels(jPanelMail);
        
        resetColor(jPanelList1);
        setColor(jPanelList2);
        resetColor(jPanelList3);
        resetColor(jPanelList4);
        resetColor(jPanelList5);
        resetColor(jPanelList6);
        resetColor(jPanelList7);
        resetColor(jPanelList8);
    }//GEN-LAST:event_jPanelList2MousePressed

    private void jPanelList3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelList3MousePressed
        // TODO add your handling code here:
        switchPanels(jPanelNhanVien);
        resetColor(jPanelList1);
        resetColor(jPanelList2);
        setColor(jPanelList3);
        resetColor(jPanelList4);
        resetColor(jPanelList5);
        resetColor(jPanelList6);
        resetColor(jPanelList7);
        resetColor(jPanelList8);
    }//GEN-LAST:event_jPanelList3MousePressed

    private void jPanelList4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelList4MousePressed
        // TODO add your handling code here:
        switchPanels(jPanelTuyen);
        
        resetColor(jPanelList1);
        resetColor(jPanelList2);
        resetColor(jPanelList3);
        setColor(jPanelList4);
        resetColor(jPanelList5);
        resetColor(jPanelList6);
        resetColor(jPanelList7);
        resetColor(jPanelList8);
    }//GEN-LAST:event_jPanelList4MousePressed

    private void jPanelList5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelList5MousePressed
        // TODO add your handling code here:
        switchPanels(jPanelChuyen);
        resetColor(jPanelList1);
        resetColor(jPanelList2);
        resetColor(jPanelList3);
        resetColor(jPanelList4);
        setColor(jPanelList5);
        resetColor(jPanelList6);
        resetColor(jPanelList7);
        resetColor(jPanelList8);
    }//GEN-LAST:event_jPanelList5MousePressed

    private void jPanelList7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelList7MousePressed
        // TODO add your handling code here:
        switchPanels(jPanelXe);
        resetColor(jPanelList1);
        resetColor(jPanelList2);
        resetColor(jPanelList3);
        resetColor(jPanelList4);
        resetColor(jPanelList5);
        resetColor(jPanelList6);
        setColor(jPanelList7);
        resetColor(jPanelList8);
    }//GEN-LAST:event_jPanelList7MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jDialog1.setSize(400, 300);
        jDialog1.setLocation(400, 300);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanelList8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelList8MousePressed
        // TODO add your handling code here:
        switchPanels(jPanelThongKe);
        resetColor(jPanelList1);
        resetColor(jPanelList2);
        resetColor(jPanelList3);
        resetColor(jPanelList4);
        resetColor(jPanelList5);
        resetColor(jPanelList6);
        resetColor(jPanelList7);
        setColor(jPanelList8);
    }//GEN-LAST:event_jPanelList8MousePressed

    private void jTableTuyenTramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTuyenTramMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel)jTableTuyenTram.getModel();
        int selectedRow = jTableTuyenTram.getSelectedRow();
        //Hien dialog tuyen tram
        jDialogTuyenTram.setSize(400, 300);
        jDialogTuyenTram.setLocation(400, 300);
        jDialogTuyenTram.setVisible(true);
        
        
        jTextFieldHieuChinhTuyen.setText(model.getValueAt(selectedRow, 0).toString());
        jTextFieldHieuChinhTram.setText(model.getValueAt(selectedRow, 1).toString());
    }//GEN-LAST:event_jTableTuyenTramMouseClicked

    private void jPanelList6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelList6MousePressed
        // TODO add your handling code here:
        switchPanels(jPanelTuyenTram);
        resetColor(jPanelList1);
        resetColor(jPanelList2);
        resetColor(jPanelList3);
        resetColor(jPanelList4);
        resetColor(jPanelList5);
        setColor(jPanelList6);
        resetColor(jPanelList7);
        resetColor(jPanelList8);
    }//GEN-LAST:event_jPanelList6MousePressed
    public void switchPanels(JPanel panel){
        jLayeredPaneQuanLy.removeAll();
        jLayeredPaneQuanLy.add(panel);
        jLayeredPaneQuanLy.repaint();
        jLayeredPaneQuanLy.revalidate();
    }
    public DefaultTableModel dtm;
    void layVe(){
        dtm= (DefaultTableModel) jTableVe.getModel();
        dtm.setNumRows(0);
        Connection ketNoi=Banvexe.layKetNoi();
        Vector vt;
        try {
            PreparedStatement ps=ketNoi.prepareStatement("select * from Ve");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                vt= new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                vt.add(rs.getString(3));
                vt.add(rs.getString(4));
                vt.add(rs.getString(5));
                vt.add(rs.getString(6));
                vt.add(rs.getString(7));
                
                dtm.addRow(vt);
                
            }
            jTableVe.setModel(dtm);
            ps.close();
            rs.close();
            ketNoi.close();
        } catch (SQLException ex) {
            System.out.println("loi lay ve");
        }
    }
    void layMail(){
        dtm= (DefaultTableModel) jTableMail.getModel();
        dtm.setNumRows(0);
        Connection ketNoi=Banvexe.layKetNoi();
        Vector vt;
        try {
            PreparedStatement ps=ketNoi.prepareStatement("select * from Mail");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                vt= new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                vt.add(rs.getString(3));
                vt.add(rs.getString(4));
                vt.add(rs.getString(5));
                
                dtm.addRow(vt);
                
            }
            jTableMail.setModel(dtm);
            ps.close();
            rs.close();
            ketNoi.close();
        } catch (SQLException ex) {
            System.out.println("loi lay mail");
        }
    }
    void layTuyenTram(){
        dtm= (DefaultTableModel) jTableTuyenTram.getModel();
        dtm.setNumRows(0);
        Connection ketNoi=Banvexe.layKetNoi();
        Vector vt;
        try {
            PreparedStatement ps=ketNoi.prepareStatement("select * from TuyenTram");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                vt= new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                
                dtm.addRow(vt);
                
            }
            jTableTuyenTram.setModel(dtm);
            ps.close();
            rs.close();
            ketNoi.close();
        } catch (SQLException ex) {
            System.out.println("loi lay khach hang");
        }
    }
    void layChuyenXe(){
        dtm= (DefaultTableModel) jTableChuyen.getModel();
        dtm.setNumRows(0);
        Connection ketNoi=Banvexe.layKetNoi();
        Vector vt;
        try {
            PreparedStatement ps=ketNoi.prepareStatement("select * from ChuyenXe");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                vt= new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                vt.add(rs.getString(3));
                vt.add(rs.getString(4));
                
                dtm.addRow(vt);
                
            }
            jTableChuyen.setModel(dtm);
            ps.close();
            rs.close();
            ketNoi.close();
        } catch (SQLException ex) {
            System.out.println("loi lay chuyen");
        }
    }
    void layXe(){
        dtm= (DefaultTableModel) jTableXe.getModel();
        dtm.setNumRows(0);
        Connection ketNoi=Banvexe.layKetNoi();
        Vector vt;
        try {
            PreparedStatement ps=ketNoi.prepareStatement("select * from Xe");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                vt= new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                
                dtm.addRow(vt);
                
            }
            jTableXe.setModel(dtm);
            ps.close();
            rs.close();
            ketNoi.close();
        } catch (SQLException ex) {
            System.out.println("loi lay xe");
        }
    }
    void layNhanVien(){
        dtm= (DefaultTableModel) jTableNhanVien.getModel();
        dtm.setNumRows(0);
        Connection ketNoi=Banvexe.layKetNoi();
        Vector vt;
        try {
            PreparedStatement ps=ketNoi.prepareStatement("select * from NhanVien");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                vt= new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                vt.add(rs.getString(3));
                vt.add(rs.getString(4));
                vt.add(rs.getString(5));
                dtm.addRow(vt);
                
            }
            jTableNhanVien.setModel(dtm);
            ps.close();
            rs.close();
            ketNoi.close();
        } catch (SQLException ex) {
            System.out.println("loi lay nhan vien");
        }
    }
    void layTuyen(){
        dtm= (DefaultTableModel) jTableTuyen.getModel();
        dtm.setNumRows(0);
        Connection ketNoi=Banvexe.layKetNoi();
        Vector vt;
        try {
            PreparedStatement ps=ketNoi.prepareStatement("select * from Tuyen");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                vt= new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                vt.add(rs.getString(3));
                
                dtm.addRow(vt);
                
            }
            jTableTuyen.setModel(dtm);
            ps.close();
            rs.close();
            ketNoi.close();
        } catch (SQLException ex) {
            System.out.println("loi lay tuyen");
        }
    }
    void layThongKeTheoNgayTT(){
        dtm= (DefaultTableModel) jTableThongKeTheoNgayTT.getModel();
        dtm.setNumRows(0);
        Connection ketNoi=Banvexe.layKetNoi();
        Vector vt;
        try {
            PreparedStatement ps=ketNoi.prepareStatement("select ngay,sum(gia)\n" +
            "from Ve,ChuyenXe\n" +
            "where ve.MaChuyenXe=ChuyenXe.MaChuyenXe \n" +
            "group by Ngay");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                vt= new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                
                dtm.addRow(vt);
                
            }
            jTableThongKeTheoNgayTT.setModel(dtm);
            ps.close();
            rs.close();
            ketNoi.close();
        } catch (SQLException ex) {
            System.out.println("loi lay TT ");
        }
    }
    void layThongKeTheoNgayVSV(){
        dtm= (DefaultTableModel) jTableThongKeTheoNgayVSV.getModel();
        dtm.setNumRows(0);
        Connection ketNoi=Banvexe.layKetNoi();
        Vector vt;
        try {
            PreparedStatement ps=ketNoi.prepareStatement("select ngay,sum(SoChoDat)\n" +
            "from Ve,ChuyenXe\n" +
            "where ve.MaChuyenXe=ChuyenXe.MaChuyenXe and MaLoaiVe='VSV'\n" +
            "group by Ngay");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                vt= new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                
                dtm.addRow(vt);
                
            }
            jTableThongKeTheoNgayVSV.setModel(dtm);
            ps.close();
            rs.close();
            ketNoi.close();
        } catch (SQLException ex) {
            System.out.println("loi lay VSV ");
        }
    }
    void layThongKeTheoNgayVT(){
        dtm= (DefaultTableModel) jTableThongKeTheoNgayVT.getModel();
        dtm.setNumRows(0);
        Connection ketNoi=Banvexe.layKetNoi();
        Vector vt;
        try {
            PreparedStatement ps=ketNoi.prepareStatement("select ngay,sum(SoChoDat)\n" +
            "from Ve,ChuyenXe\n" +
            "where ve.MaChuyenXe=ChuyenXe.MaChuyenXe and MaLoaiVe='VT'\n" +
            "group by Ngay");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                vt= new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                
                dtm.addRow(vt);
                
            }
            jTableThongKeTheoNgayVT.setModel(dtm);
            ps.close();
            rs.close();
            ketNoi.close();
        } catch (SQLException ex) {
            System.out.println("loi lay VT ");
        }
    }

    
    void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(64,43,100));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialogTuyenTram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPaneQuanLy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelChuyen;
    private javax.swing.JPanel jPanelList;
    private javax.swing.JPanel jPanelList1;
    private javax.swing.JPanel jPanelList2;
    private javax.swing.JPanel jPanelList3;
    private javax.swing.JPanel jPanelList4;
    private javax.swing.JPanel jPanelList5;
    private javax.swing.JPanel jPanelList6;
    private javax.swing.JPanel jPanelList7;
    private javax.swing.JPanel jPanelList8;
    private javax.swing.JPanel jPanelMail;
    private javax.swing.JPanel jPanelNhanVien;
    private javax.swing.JPanel jPanelThongKe;
    private javax.swing.JPanel jPanelTuyen;
    private javax.swing.JPanel jPanelTuyenTram;
    private javax.swing.JPanel jPanelVe;
    private javax.swing.JPanel jPanelXe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTableChuyen;
    private javax.swing.JTable jTableMail;
    private javax.swing.JTable jTableNhanVien;
    private javax.swing.JTable jTableThongKeTheoNgayTT;
    private javax.swing.JTable jTableThongKeTheoNgayVSV;
    private javax.swing.JTable jTableThongKeTheoNgayVT;
    private javax.swing.JTable jTableTuyen;
    private javax.swing.JTable jTableTuyenTram;
    private javax.swing.JTable jTableVe;
    private javax.swing.JTable jTableXe;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldHieuChinhTram;
    private javax.swing.JTextField jTextFieldHieuChinhTuyen;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
