/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banvexe;
import java.awt.Color;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
/**
 *
 * @author Huu Nhan
 */
public class vexe extends javax.swing.JFrame {

    /**
     * Creates new form vexe
     */
    
    public vexe() {
        initComponents();
        
    }
    public int ktUser(String email,String pass){
        int ok=0;
        Connection ketNoi=Banvexe.layKetNoi();
        try{
            PreparedStatement ps= ketNoi.prepareStatement("select Email,Pass from Mail");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
               
               if(rs.getString("Email").equalsIgnoreCase(email)&&rs.getString("Pass").equalsIgnoreCase(pass)) {
                   
                   ok = 1;
                   break;
               }else{
                   ok = 0;
               }
            }
            
        }catch(SQLException e){
            System.out.println("loi lay tuyen");
        }
        return ok;
    }
    public void luuTaiKhoan(String email,String ten,String sdt,String matKhau,float soDu){
        Connection ketNoi=Banvexe.layKetNoi();
        try{
            PreparedStatement ps= ketNoi.prepareStatement("insert into Mail values(?,?,?,?,?)");
            ps.setString(1, email);
            ps.setString(2, ten);
            ps.setString(3, sdt);
            ps.setString(4, matKhau);
            ps.setFloat(5, soDu);
            ps.executeUpdate();
        }catch(SQLException e){
            System.out.println("loi luu chuyen xe");
        }
    }
    public int kiemTraEmail(String email){
        Connection ketNoi=Banvexe.layKetNoi();
        try{
            PreparedStatement ps= ketNoi.prepareStatement("select Email from Mail");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                if(rs.getString("Email").equalsIgnoreCase(email)){
                    return 1;
                }
            }
        }catch(SQLException e){
            System.out.println("loi lay email");
        }
        return 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowsButtonUI1 = new com.jgoodies.looks.windows.WindowsButtonUI();
        windowsButtonUI2 = new com.jgoodies.looks.windows.WindowsButtonUI();
        windowsButtonUI3 = new com.jgoodies.looks.windows.WindowsButtonUI();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jTextFieldDKEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDKTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDKSDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDKMK = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonDangKy = new javax.swing.JButton();
        kGradientPanelVeXe = new keeptoo.KGradientPanel();
        jLabelHome = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelThoat = new javax.swing.JLabel();
        jPanelDangNhap = new javax.swing.JPanel();
        jLabelDangNhap = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldMatKhau = new javax.swing.JTextField();
        jLabelButtonDangNhap = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelDKTK = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jLabel4.setText("Email");

        jLabel5.setText("Tên ");

        jLabel6.setText("SDT");

        jLabel7.setText("Mật khẩu");

        jButtonDangKy.setText("Đăng ký");
        jButtonDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangKyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(65, 65, 65)
                        .addComponent(jTextFieldDKMK))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldDKSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldDKTen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jTextFieldDKEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButtonDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDKEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDKTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDKSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDKMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(43, 43, 43)
                .addComponent(jButtonDangKy)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHome.setBackground(new java.awt.Color(51, 51, 51));
        jLabelHome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(51, 51, 51));
        jLabelHome.setText("VEXEBUS");

        jLabelLogo.setIcon(new javax.swing.ImageIcon("D:\\Nhap mon cong nghe phan mem\\banvexe\\icons8_bus_40px_1.png")); // NOI18N

        jLabelThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelThoat.setForeground(new java.awt.Color(255, 255, 255));
        jLabelThoat.setText("Thoát");
        jLabelThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanelVeXeLayout = new javax.swing.GroupLayout(kGradientPanelVeXe);
        kGradientPanelVeXe.setLayout(kGradientPanelVeXeLayout);
        kGradientPanelVeXeLayout.setHorizontalGroup(
            kGradientPanelVeXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanelVeXeLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                .addComponent(jLabelThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        kGradientPanelVeXeLayout.setVerticalGroup(
            kGradientPanelVeXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanelVeXeLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(kGradientPanelVeXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLogo)
                    .addGroup(kGradientPanelVeXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHome)
                        .addComponent(jLabelThoat)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(kGradientPanelVeXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        jLabelDangNhap.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabelDangNhap.setText("ĐĂNG NHẬP");

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jTextFieldMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatKhauActionPerformed(evt);
            }
        });

        jLabelButtonDangNhap.setBackground(new java.awt.Color(0, 0, 0));
        jLabelButtonDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login_50px.png"))); // NOI18N
        jLabelButtonDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonDangNhapMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Email ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mật khẩu");

        jLabelDKTK.setForeground(new java.awt.Color(0, 102, 255));
        jLabelDKTK.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelDKTK.setText("Đăng kí tài khoản");
        jLabelDKTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDKTKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelDangNhapLayout = new javax.swing.GroupLayout(jPanelDangNhap);
        jPanelDangNhap.setLayout(jPanelDangNhapLayout);
        jPanelDangNhapLayout.setHorizontalGroup(
            jPanelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDangNhapLayout.createSequentialGroup()
                .addGroup(jPanelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDangNhapLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabelDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDangNhapLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(100, 100, 100)
                        .addGroup(jPanelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDangNhapLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDangNhapLayout.createSequentialGroup()
                        .addComponent(jLabelButtonDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDangNhapLayout.createSequentialGroup()
                        .addComponent(jLabelDKTK)
                        .addGap(348, 348, 348))))
        );
        jPanelDangNhapLayout.setVerticalGroup(
            jPanelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDangNhapLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelDangNhap)
                .addGap(81, 81, 81)
                .addGroup(jPanelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(jPanelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jLabelButtonDangNhap)
                .addGap(70, 70, 70)
                .addComponent(jLabelDKTK)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 800, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelThoatMouseClicked
        // TODO add your handling code here:
        jLabelThoat.setBackground(Color.WHITE);
        System.exit(0);
    }//GEN-LAST:event_jLabelThoatMouseClicked

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatKhauActionPerformed

    private void jLabelButtonDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonDangNhapMouseClicked
        // TODO add your handling code here:
        if(ktUser(jTextFieldEmail.getText(),jTextFieldMatKhau.getText())==1){
            System.out.println("cho nay");
            new muave(jTextFieldEmail.getText()).setVisible(true);
            this.dispose();
        }
        else if(jTextFieldEmail.getText().equalsIgnoreCase("admin")&&jTextFieldMatKhau.getText().equalsIgnoreCase("admin")){
            new quanli().setVisible(true);
            this.dispose();
        }else{
            System.out.println("sai thong tin dang nhap");
        }
        
    }//GEN-LAST:event_jLabelButtonDangNhapMouseClicked

    private void jLabelDKTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDKTKMouseClicked
        // TODO add your handling code here:
        jDialog1.setSize(400, 300);
        jDialog1.setLocation(400, 300);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jLabelDKTKMouseClicked

    private void jButtonDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangKyActionPerformed
        // TODO add your handling code here:
        String email=jTextFieldDKEmail.getText();
        String ten=jTextFieldDKTen.getText();
        String sdt=jTextFieldDKSDT.getText();
        String matKhau=jTextFieldDKMK.getText();
        float soDu=0;
        if(kiemTraEmail(email)==0&&email!=null&&ten!=null&&sdt!=null&&matKhau!=null){
            luuTaiKhoan(email, ten, sdt, matKhau,soDu );
            System.out.println("Dang ki tai khoan thanh cong. Moi dang nhap.");
            JOptionPane.showMessageDialog(this, "Dang ki tai khoan thanh cong. Moi dang nhap.");
            jDialog1.dispose();
        }else{
            System.out.println("Email da ton tai");
            JOptionPane.showMessageDialog(this, "Email da ton tai hoac thieu thong tin");
        }
        
    }//GEN-LAST:event_jButtonDangKyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vexe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDangKy;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelButtonDangNhap;
    private javax.swing.JLabel jLabelDKTK;
    private javax.swing.JLabel jLabelDangNhap;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelThoat;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanelDangNhap;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField jTextFieldDKEmail;
    private javax.swing.JTextField jTextFieldDKMK;
    private javax.swing.JTextField jTextFieldDKSDT;
    private javax.swing.JTextField jTextFieldDKTen;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldMatKhau;
    private keeptoo.KGradientPanel kGradientPanelVeXe;
    private com.jgoodies.looks.windows.WindowsButtonUI windowsButtonUI1;
    private com.jgoodies.looks.windows.WindowsButtonUI windowsButtonUI2;
    private com.jgoodies.looks.windows.WindowsButtonUI windowsButtonUI3;
    // End of variables declaration//GEN-END:variables


}
